### ISSUE TITLE
Create a button to get time

### ISSUE THREAD

**Issue by jrvelloso** [rrnazario/youtube-jumper#2]
Instead of typing the time to jump, click on a button and it creates the interval.

Onclick: 

Analyse if 
 * already have others timers and keep those, ex

    3:42->4:18
    7:55->8:06

 * already have the begining time

    3:42->4:18
    7:55->8:06
    11:06

* already have "->"for the new interval, ex
    3:42->4:18
    7:55->8:06
    11:06->

* already the end of the previous interval, ex
    3:42->4:18
    7:55->8:06
    11:06->12:07

**Comment by rrnazario** [comment]
Was implemented a button that captures the time:

![image](https://user-images.githubusercontent.com/7026130/174475620-9c361139-61c7-47af-bb86-24a9430e671a.png)
