### ISSUE TITLE
Enable the cinema view button

### ISSUE THREAD

**Issue by jrvelloso** [rrnazario/youtube-jumper#4]
![image](https://user-images.githubusercontent.com/23175337/168435513-dbeb5693-7f68-4323-b304-78e7bde982cc.png)

should be:

![image](https://user-images.githubusercontent.com/23175337/168435595-e44d560b-102e-42f9-a684-ac68b469dff9.png)

**Comment by rrnazario** [comment]
See https://developers.google.com/youtube/player_parameters.html?playerVersion=HTML5#controls
